services:
  - type: web
    name: cryptopirate
    env: python
    plan: free

    # Force a clean, explicit build
    buildCommand: |
      python -V
      python -m pip install --upgrade pip
      pip install -r requirements.txt

    # Start your app
    startCommand: python platform.py --serve

    autoDeploy: true

    # Declare env vars; you’ll set values in the Render UI
    envVars:
      - key: APP_FERNET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENGINE_RUN
        value: "1"
